# Site settings
title: Script everything
description: > # this means to ignore newlines until "baseurl:"
  The purpose of this site is evolving. But it seems
  to be related to programming and scriptifying whenever possible.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zenonharley.com" # the base hostname & protocol for your site
twitter_username: zenonharley
github_username:  zharley

# Build settings
markdown: kramdown
